### ISSUE TITLE
Missing Apple icons and existing icon problems

### ISSUE THREAD

**Issue by MarkSmit** [edent/SuperTinyIcons#131] opened 2018-02-10 10:08 UTC
New icons:
* Name: Apple Music
* URL: [Apple Music website](https://apple.com/apple-music)
* Link to icon: [Apple Music icon](https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/d2/cf/1e/d2cf1e56-a429-c4cb-e973-c53f01176bdb/AppIcon-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-9.png/738x0w.jpg)
-----
* Name: Apple Podcasts
* URL: [Apple Podcasts website](https://www.apple.com/itunes/podcasts/)
* Link to icon: [Apple Podcasts icon](https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/bb/45/69/bb45692f-2d72-9d98-f802-918d0f560624/mzl.liqqlbrn.png/738x0w.jpg)
-----
* Name: App Store
* URL: [App Store website](appstore.com)
* Link to icon: [App Store icon](https://images.apple.com/v/ios/app-store/b/images/overview/app_store_icon_large_2x.jpg)
-----
* Name: Apple Maps
* URL: [Apple Maps website](maps.apple.com)
* Link to icon: [Apple Maps icon](https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/1d/12/10/1d12104a-ce4e-68e0-e8b2-76c9487f8890/mzl.vecqidkx.png/738x0w.jpg)
-----
* Name: Apple Homekit
* URL: [Apple Homekit website](apple.com/homekit)
* Link to icon: [Apple Homekit icon](https://is4-ssl.mzstatic.com/image/thumb/Purple71/v4/1c/86/3c/1c863c3e-c93b-548a-1eb0-09460284b10f/mzl.hpkipaqm.png/738x0w.jpg)

These are very useful for when you want to share your content on one of these platforms, like music playlists or locations in maps.

Some things about existing icons:
* The instagram icon doens have the gradient as shown on the [real icon](https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/e6/95/bf/e695bfa6-9e66-625f-c7a4-6365ac3fd366/Prod-1x_U007emarketing-85-220-0-5.png/738x0w.jpg)
* The Apple icon should be reversed in colors, like [here](https://pbs.twimg.com/profile_images/856508346190381057/DaVvCgBo_400x400.jpg). Also the apple is a bit too big in your icon.
* The current YouTube icon looks like the old icon. [Currently](https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/30/80/29/308029a6-38d5-fbcc-ccef-b104d04dfd87/AppIcon-1x_U007emarketing-85-220-0-6.png/738x0w.jpg) it has a other red color and also the play button is red instead of the box. (Maybe you can make two versions of the logos, like twitter can also be both).

**Comment by edent** [comment] 2018-02-11 16:45
Thanks! These look like good ideas. Can you add them?

**Comment by MrkSmt** [comment] 2018-02-20 19:06
Sorry, I don't know how SVG works exactly, so I only thought it was handy to add them to a 'to do'-list as suggestions

**Comment by MarkSmit** [comment] 2018-02-28 12:49
The Apple Music svg looks good in Chrome, but not in Safari. It looks like the gradients are stacked upon each other. 
Chrome: <img width="200px" alt="schermafbeelding 2018-02-27 om 21 07 47" src="https://user-images.githubusercontent.com/31420655/36752118-5fc02a08-1c02-11e8-9f8e-8393292b256c.png">
Safari: <img width="200px" alt="schermafbeelding 2018-02-27 om 21 08 06" src="https://user-images.githubusercontent.com/31420655/36752126-6ac6e694-1c02-11e8-99ee-be52674b2eb9.png">

Also another icon that's missing:
- Name: Dribbble
- URL: [Dribbble webiste](http://dribbble.com)
- Link to icon: [Dribbble icon](http://icons.iconarchive.com/icons/danleech/simple/1024/dribbble-icon.png)

I also changed the instagram icon to a gradient version, maybe this could be added as an additional instagram icon:
`<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Instagram" role="img"
viewBox="0 0 512 512">
<radialGradient id="a" r="150%" cx="30%" cy="107%"><stop stop-color="#fdf497" offset="0"></stop><stop stop-color="#fdf497" offset="0.05"></stop><stop stop-color="#fd5949" offset="0.45"></stop><stop stop-color="#d6249f" offset="0.6"></stop><stop stop-color="#285AEB" offset="0.9"></stop></radialGradient><rect
width="512" height="512"
rx="15%"
fill="url(#a)"/><g fill="none" stroke="#fff" stroke-width="29"><rect height="296" rx="78" width="296" x="108" y="108"/><circle cx="256" cy="256" r="69"/></g><circle cx="343" cy="169" fill="#fff" r="19"/></svg>
`

**Comment by baybal** [comment] 2018-02-28 15:12
@edent what do you think?

**Comment by baybal** [comment] 2018-02-28 15:14
@MarkSmit Safari is not standard compliant...

**Comment by edent** [comment] 2018-02-28 15:51
@MarkSmit please add the Dribble request as a new issue.

@baybal icons need to work in *all* browsers. I suggest monochrome if it doesn't work as a gradient.

**Comment by baybal** [comment] 2018-02-28 16:01
@MarkSmit is your Safari version any much recent?

**Comment by baybal** [comment] 2018-02-28 16:12
Can somebody with macos check if this is happening in the latest safari?

**Comment by MarkSmit** [comment] 2018-02-28 16:24
@baybal Yes, it's the latest version of Safari (11.0.3) and also in Safari on iOS 11.3 beta 3
@edent I will make a new issue for dribble

**Comment by baybal** [comment] 2018-02-28 16:26
how does it look if you change `#fff0` to `#ffffff00` ?

**Comment by MarkSmit** [comment] 2018-02-28 16:33
@baybal That doesn't change the icon, it stays the same.

**Comment by MarkSmit** [comment] 2018-02-28 16:44
@baybal  I searched on the internet and found that you should use `stop-color="#fff" stop-opacity="0"` instead of `stop-color="#fff0"` and that seems to work when I test it.

**Comment by baybal** [comment] 2018-02-28 16:47
@MarkSmit what if you use rgba(255,255,255,0) instead?

**Comment by MarkSmit** [comment] 2018-02-28 16:51
@baybal doesn't seem to work either. Can you check if `stop-opacity` is working in chrome, because if it is, that is the solution.

**Comment by baybal** [comment] 2018-02-28 16:53
@MarkSmit I know that it is the cause. I was testing if Safari can't handle RGBA as hex or it simply can't take any RGBA as a stop colour.

**Comment by baybal** [comment] 2018-03-05 06:41
@edent  what is possible: we can throw out the inset shadow filter and try to blend over one gradient over the background. This will win us enough of space to get the second transparent gradient the way safari can handle. Another thing that can be tried is to use a single alpha gradient, and use it as a mask for solid color filled icon layers.

**Comment by edent** [comment] 2018-03-05 09:45
Do it 😀

**Comment by edent** [comment] 2018-05-30 07:39
Does this still need fixing?

**Comment by baybal** [comment] 2018-06-02 05:09
It does. Changes needed are trivial, but I don't have time even for that now.

**Comment by romain-dartigues** [comment] 2019-10-08 07:50
Note, reference to the Apple brand at: https://developer.apple.com/softwarelicensing/.
Most of the icons are downloadable in vector format in their pages.
Some others need digging, such as: https://developer.apple.com/swift/resources/

**Comment by edent** [comment] 2020-11-08 12:32
Apple have changed their logo, and we've updated. So closing this issue.

**Closed by edent** 2020-11-08 12:32 UTC
